[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "weather-station"
version = "0.0.3"
dependencies = [
  "lxml",
  "requests"
]

[tool.setuptools.packages]
find = {}
